### ISSUE TITLE
Harmony Trailblazer Path is set to "Hunt"

### ISSUE THREAD

**Issue by IanKatsy** [IceDynamix/reliquary-archiver#16]
0.1.6
Happens in 2.2

![image](https://github.com/IceDynamix/reliquary-archiver/assets/117476578/204a8147-3249-4fe3-b0e9-f711b81a8c79)

**Comment by Tor1me** [comment]
^ same thing, all artifacts exported as "Hunt" TB instead of Harmony (
![Notepad_VoD1wAcSiV](https://github.com/IceDynamix/reliquary-archiver/assets/104445491/1303d310-dcab-4c7e-861a-7074b5e8c918)

**Comment by IceDynamix** [comment]
fixed with #22
