### ISSUE TITLE
Application force closes upon logging into game

### ISSUE THREAD

**Issue by Exkalamity** [IceDynamix/reliquary-archiver#17]
As title says, I run the program, log into game, and as the train goes hyperdrive, the application quits. From what I can tell, once I start logging in, only one line of output prints after the "Waiting with timeout 120secs" line before the whole thing force closes. I think it reads "connection established" but it closes too fast for me to see thing whole thing. I wish I could provide a screenshot, but I'm not fast enough to capture that output before the exe closes itself.

**Comment by DragonQuestXI** [comment]
I can't run as the same reason

**Comment by way2temple** [comment]
I encountered the same situation, after running the program, the window closed quickly, after several attempts I took a screenshot successfully, provided to you guys hope to help
![微信图片_20240515025300](https://github.com/IceDynamix/reliquary-archiver/assets/162630334/f38af4b8-49ed-4ff3-82a3-d7650d5b3c10)

**Comment by FaeronGaming** [comment]
If anyone is still having trouble capturing output you can run the exe from within a terminal of your own.

![image](https://github.com/IceDynamix/reliquary-archiver/assets/3262183/46918934-a2ff-47a3-8443-3c396e7e3044)

This way should the exe crash the terminal would remain open.

**Comment by way2temple** [comment]
![image](https://github.com/IceDynamix/reliquary-archiver/assets/162630334/5888cdd5-81a6-407a-a1d9-4b24411ad7d6)
Thank you very much, I know it takes a lot of patience to answer such simple and silly questions, but I still get this hint when running in CMD :(

**Comment by Exkalamity** [comment]
> ![image](https://private-user-images.githubusercontent.com/162630334/330936322-5888cdd5-81a6-407a-a1d9-4b24411ad7d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MDU0NTcsIm5iZiI6MTcxNTgwNTE1NywicGF0aCI6Ii8xNjI2MzAzMzQvMzMwOTM2MzIyLTU4ODhjZGQ1LTgxYTYtNDA3YS1hMWQ5LTRiMjQ0MTFhZDdkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQyMDMyMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGFkNzU3NDYzZjBhYWFiNGYxNzQ2MTk4MzJkMDY0ODc5ZTQwOTBhNzhkMzYxZDJkYTlkMTkxZGYwZTAzMjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TGgaueXHu6hj6It52cQsQGadJ1OJ0rE8HXcVirbCdIY) Thank you very much, I know it takes a lot of patience to answer such simple and silly questions, but I still get this hint when running in CMD :(

I agree I just did the cmd prompt trick and I got the same response.

**Comment by FaeronGaming** [comment]
@Exkalamity @way2temple The goal of running was never to fix the crashing itself, but to get the logging needed to understand why the crash is occurring. Thanks to the two of you, we can see an `InvalidCertificate(UnknownIssuer)` TLS error is being thrown trying to hit the Dimbreath/StarRailData repo.

I find it odd the problem is occurring, but I could very well be misunderstanding something. `ureq` has `tls` enabled by default, which includes `webpki-roots`, so in theory this error shouldn't happen. Could this be something resolvable with enabling `native-certs`? Only other thing I can come up with is whether or not these requests are getting caught by some proxy

**Comment by gongfuture** [comment]
> @Exkalamity @way2temple The goal of running was never to fix the crashing itself, but to get the logging needed to understand why the crash is occurring. Thanks to the two of you, we can see an `InvalidCertificate(UnknownIssuer)` TLS error is being thrown trying to hit the Dimbreath/StarRailData repo.
> 
> I find it odd the problem is occurring, but I could very well be misunderstanding something. `ureq` has `tls` enabled by default, which includes `webpki-roots`, so in theory this error shouldn't happen. Could this be something resolvable with enabling `native-certs`? Only other thing I can come up with is whether or not these requests are getting caught by some proxy

I think you are right. I use a proxy to connect github and met this problem too. These messages disappear when I turn off the proxy, but I also cant connect github :( Just stuck in the initialize

**Comment by gongfuture** [comment]
> > @Exkalamity @way2temple The goal of running was never to fix the crashing itself, but to get the logging needed to understand why the crash is occurring. Thanks to the two of you, we can see an `InvalidCertificate(UnknownIssuer)` TLS error is being thrown trying to hit the Dimbreath/StarRailData repo.
> > 
> > I find it odd the problem is occurring, but I could very well be misunderstanding something. `ureq` has `tls` enabled by default, which includes `webpki-roots`, so in theory this error shouldn't happen. Could this be something resolvable with enabling `native-certs`? Only other thing I can come up with is whether or not these requests are getting caught by some proxy
> 
> I think you are right. I use a proxy to connect github and met this problem too. These messages disappear when I turn off the proxy, but I also cant connect github :( Just stuck in the initialize

Also I think that the problem @way2temple met is different from this issue, just my opinion

**Comment by FaeronGaming** [comment]
> > Also I think that the problem @way2temple met is different from this issue, just my opinion
> 
> You were right. I used the cmd prompt to capture the error and it's markedly different from @way2temple.
> 
> https://i.imgur.com/OeHf7fR.png
> 
> Here is my error message.

You are using version `0.1.4`. Use the latest `0.1.6`.

**Comment by Exkalamity** [comment]
> ###
> **[FaeronGaming](/FaeronGaming) ** commented [May 15, 2024](#issuecomment-2114122776)

That was it lol. I don't know why I wasn't seeing the most recent version. Thanks!

**Comment by FaeronGaming** [comment]
@way2temple your issue is the same as #13
