### ISSUE TITLE
После использования на главном меню при выходе из игры или аккаунта испанский язык вместо русского

### ISSUE THREAD

**Issue by Makishimu120** [IceDynamix/reliquary-archiver#3]
На фото видно, что включен русский язык в настройках(подписи кнопок русские).
проверку ресурсов делал, ничего не нашло.
Еще когда запускаешь игру, сверху "Добро пожаловать "почта@mail.ru"" стало тоже на испанском.
В других местах такого не обнаружено.
Не могу на все 100% утверждать что это из-за сканера, но такое я заметил только сегодня
![image](https://github.com/IceDynamix/reliquary-archiver/assets/74831656/b11fce3a-9d5b-4ced-8062-4de58b93c1c8)
![image](https://github.com/IceDynamix/reliquary-archiver/assets/74831656/4b0f2266-9f26-41eb-a37d-cd9aa3ecdc57)

**Comment by IceDynamix** [comment]
reliquary archiver does not modify any game files, i don't see how this issue is related

**Comment by Makishimu120** [comment]
HKEY_CURRENT_USER\SOFTWARE\Cognosphere\Star Rail\SDK_LANG_FILE_ru_2_h2358261870
