### ISSUE TITLE
The application panicked (crashed) - Game Version 2.3

### ISSUE THREAD

**Issue by emb3rlight** [IceDynamix/reliquary-archiver#32]
Hey guys, 

Application is amazing. Is there any plan to support current patch of the game 2.3? Getting the error below since the update. 

Thanks for all your amazing work!

2024-06-20T20:43:20.009206Z  INFO live_capture: reliquary_archiver: detected connection established
The application panicked (crashed).
Message:  range end index 546923644 out of range for slice of length 996
Location: C:\Users\Ice\.cargo\git\checkouts\reliquary-273ee92fcf463098\add4b40\src\network\mod.rs:131

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Warning: SpanTrace capture is Unsupported.
Ensure that you've setup a tracing-error ErrorLayer and the semver versions are compatible

**Comment by IceDynamix** [comment]
yes, i'll update it in the next few days. just getting a bit hectic because i'm on vacation rn lol

**Comment by emb3rlight** [comment]
> yes, i'll update it in the next few days. just getting a bit hectic because i'm on vacation rn lol

Thanks for your reply.
No worries, no rush, have a good vacation!

**Comment by IceDynamix** [comment]
https://github.com/IceDynamix/reliquary-archiver/releases/tag/v0.1.7
