### ISSUE TITLE
Achievement Tracking

### ISSUE THREAD

**Issue by Sylencia** [IceDynamix/reliquary-archiver#38]
This is more of a question of possibility than necessarily a suggestion to do given the limited scope of this specific repo - can this method be used to grab a list of the player's achievements? There are few ways that I have found to get the list of achievements done outside of some offshoot OCR methods and straight up manual checks so I figured this would make things a lot simpler if possible.

**Comment by IceDynamix** [comment]
https://github.com/juliuskreutz/stardb-exporter

**Comment by Sylencia** [comment]
Thanks, that somehow slipped through my searches.
