### ISSUE TITLE
Win11: Executable is not a valid application for this OS Platform

### ISSUE THREAD

**Issue by suntree123** [IceDynamix/reliquary-archiver#40]
I'm on Windows 11. Running the executable by either clicking on it or running it on the PowerShell command line fails with the error "The specified executable is not a valid application for this OS platform." Any idea why this is happening?

![image](https://github.com/IceDynamix/reliquary-archiver/assets/174636016/3155ef04-df4b-49aa-b7b2-c99356c8a96f)

**Comment by FaeronGaming** [comment]
Something is definitely going on, but I don't think it's OS related. Runs just fine with both Win11 AND PS.

![image](https://github.com/IceDynamix/reliquary-archiver/assets/3262183/6f1993d2-4d4f-44e8-9f8c-d514ea02881c)

I haven't been able to find anything concrete with that error message yet, but I'll still dig. Two items came up so far; the first being "compiled for 64-bit, but running on 32", but that's impossible as there's no 32-bit version of Win11. The second is possibility of the exe getting deleted by your antivirus, which is highly plausible considering the recent issues with the app getting flagged.

**Comment by Zxilly** [comment]
Maybe your download failed and got an empty file. Check the file size and compared it with the size on the release page.
