### ISSUE TITLE
Initializing Database - Failed to Read JSON

### ISSUE THREAD

**Issue by Daniel-Poke** [IceDynamix/reliquary-archiver#44]
In the last 48 hrs launching `reliquary-archiver_x64_v0.1.7` is crashing on the initializing database step:

```
2024-07-29T11:20:55.387278Z  INFO config_map: reliquary_archiver::export::fribbels: initializing database from online sources, this might take a while...
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Failed to read JSON: invalid type: sequence, expected a map at line 1 column 1" }
Location: src\export\fribbels.rs:302

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Warning: SpanTrace capture is Unsupported.
Ensure that you've setup a tracing-error ErrorLayer and the semver versions are compatible
```
As others have mentioned, having a local/cached version of the database would go a long way in helping those with bad connections, proxy requirements or unhandled database changes.

**Comment by ManuSwaG** [comment]
I can confirm I have the same issue:

`PS D:\Data\Games\Nonsteam\Honkai star rail Relic Importer> .\reliquary-archiver_x64_v0.1.7.exe
2024-07-29T14:08:11.872611Z  INFO config_map: reliquary_archiver::export::fribbels: initializing database from online sources, this might take a while...
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Failed to read JSON: invalid type: sequence, expected a map at line 1 column 1" }
Location: src\export\fribbels.rs:302

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Warning: SpanTrace capture is Unsupported.
Ensure that you've setup a tracing-error ErrorLayer and the semver versions are compatible`

**Comment by RaccoonBlade** [comment]
I have the same issue

**Comment by Arthra-X** [comment]
Same exact issue here, I agree with what Daniel-Poke said

**Comment by Daniel-Poke** [comment]
Had a quick peek in source, the database in question is probably related to the static files in [this](https://github.com/Dimbreath/StarRailData) repository from Dimbreath.

There's a fairly large update from ~20hrs ago which is probably what knocked out the downloading/parsing.

**Comment by zekesulastin** [comment]
Per Fribbels on Discord and tying into the warning on the optimizer Import page:

scanner will be down until after the 2.4 patch, if anyone wants to run it before the new reliquary update, clone and change https://github.com/IceDynamix/reliquary-archiver/blob/main/src/export/fribbels.rs#L32
to:
`const BASE_RESOURCE_URL: &str = "https://raw.githubusercontent.com/Dimbreath/StarRailData/df89dd1138e751c8b1a62c92fc2bafac421dc18f";`
then build/run as normal

![IMG_4752](https://github.com/user-attachments/assets/e7e01542-9a7e-4c58-900c-4378389d4062)

**Comment by Daniel-Poke** [comment]
Thanks for passing on this information. Confirmed that using the commit hash edit suggested will get it working again.

This would make for a pretty useful command line argument as well, if a local version of the db is more trouble than it's worth:

`reliquary-archiver.exe --db-hash "df89dd1138e751c8b1a62c92fc2bafac421dc18f"`
