### ISSUE TITLE
Reliquary is crashing the instant I opened it

### ISSUE THREAD

**Issue by TainiuKu** [IceDynamix/reliquary-archiver#45]
It was working fine yesterday but now the cmd seems to be shutting the instant I opened it. I've tried redownloading the exe and also restarted my PC but it still just shuts down the instant I opened the exe.

**Comment by MikaDev0X** [comment]
Same issue here:
2024-07-30T15:26:35.279966Z  INFO config_map: reliquary_archiver::export::fribbels: initializing database from online sources, this might take a while...
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "Failed to read JSON: invalid type: sequence, expected a map at line 1 column 1" }
Location: src\export\fribbels.rs:302

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: BaseThreadInitThunk<unknown>
      at <unknown source file>:<unknown line>
   2: RtlUserThreadStart<unknown>
      at <unknown source file>:<unknown line>

**Comment by Blazorthecat** [comment]
Up.
Same problem here!

**Comment by PTracana** [comment]
It's down until there is a patch 2.4 version. @Blazorthecat @TainiuKu
