### ISSUE TITLE
BitDefender started to have an issue with the new version

### ISSUE THREAD

**Issue by azur3wrath** [IceDynamix/reliquary-archiver#50]
Im having a permanent hit on the new executable with Gen:Variant.Tedy.607416 by BitDefender.
Do you know by any chance if its a false positive?

**Comment by Mimo-Bn** [comment]
i'm having a similar issue with my norton flagging it

**Comment by IceDynamix** [comment]
duplicate of https://github.com/IceDynamix/reliquary-archiver/issues/36
