### ISSUE TITLE
Reliquary not launching/not detecting the game

### ISSUE THREAD

**Issue by Pajkaa** [IceDynamix/reliquary-archiver#57]
I tried launching it today from the previous version (I still had the 0.1.7 version) and it didn't do anything after opening. I downloaded the newest release, read a bit, and from issue #37, I learned I can launch it from CMD. Did that, however it seems that it's not detecting the game. 
![image](https://github.com/user-attachments/assets/ba3a5a43-c6f0-4152-8696-40a842ae0ae0)
After those 120s, I pressed enter and got this.
![image](https://github.com/user-attachments/assets/a8d83de8-6430-4d47-a0ca-d19cc159f6c2)

**Comment by IceDynamix** [comment]
once it says "listening with timeout" you actually have to go *into* the game. check the [instructions](https://github.com/IceDynamix/reliquary-archiver?tab=readme-ov-file#run) and refer to the gif at the end

**Comment by Pajkaa** [comment]
Yeah I know, I've used it before. Still the same thing happens

**Comment by IceDynamix** [comment]
try enabling/disabling vpn or using a different network

**Comment by IceDynamix** [comment]
closed for inactivity
