### ISSUE TITLE
SPD returning decimal value

### ISSUE THREAD

**Issue by TheFarix** [IceDynamix/reliquary-archiver#58]
reliquary-archiver version: v0.1.10
HSR version: 2.4

Instead of returning integer values for SPD, decimal values are being captured.

![Screenshot 2024-09-03 210458](https://github.com/user-attachments/assets/e3901800-a51e-4c40-80db-b3e4f058f944)

[archive_output.json](https://github.com/user-attachments/files/16859411/archive_output.json)

**Comment by FichteFoll** [comment]
That's what the speed values are. The game just rounds/truncates them in its UI for some odd reason.
