### ISSUE TITLE
Crashes when the game logs in

### ISSUE THREAD

**Issue by john-bao-git** [IceDynamix/reliquary-archiver#61]
The command prompt suddenly closes itself when I log into the game. I can't input any commands when I run the .exe file either. I don't see any logs to look at either.

I managed to get this to work last time, but now it's not working. I also waited for a couple days after 2.5 dropped since this was supposed to be down. If this is happening, is it still down?

I use ethernet cable and I don't use VPN.

**Comment by IceDynamix** [comment]
i've pushed a new version 0.1.11 for game version 2.5, can you see if it works?

**Comment by john-bao-git** [comment]
Hello,

It looks like it worked. Thanks!
