### ISSUE TITLE
Unable to build on Linux

### ISSUE THREAD

**Issue by Evas1oN** [IceDynamix/reliquary-archiver#67]
OS: Arch Linux
Kernel: Linux 6.10.9-arch1-2
libpcap installed
![Picture](https://github.com/user-attachments/assets/ba5bfd1e-c959-44de-99d4-c34900de7200)
Tried it on different distros (Fedora, Ubuntu), still get the error

**Comment by FichteFoll** [comment]
Is this with 0.1.13, i.e. current `main`? The ref used in the reliquary path is for the old one, so I suspect it is not.  This issue was specifically fixed in that release.

**Comment by BobAarons** [comment]
I had the same issue, just had to bump the tag for reliquary in Cargo.toml to `v5.1.0`

**Comment by Evas1oN** [comment]
Thank you, that was the issue.
Why did it build well on Windows? It should face the same issue
https://github.com/IceDynamix/reliquary-archiver/actions/runs/11521024737/job/32074036287

**Comment by FichteFoll** [comment]
Huh, you're right. Guess @IceDynamix forgot to update the ref.

https://github.com/IceDynamix/reliquary-archiver/blob/5182e770640a5e0f5c15de0ade5b919c0c8c9ae6/Cargo.toml#L24

It worked for me locally because I used my locally modified version of reliquary to build.

**Comment by IceDynamix** [comment]
apologies for forgetting to update the rq tag, but how did it compile in ci??

**Comment by FichteFoll** [comment]
CI builds on Windows and Windows didn't have this issue to begin with.
