### ISSUE TITLE
Problem building, missing PlayerHeartBeatCsReq/PlayerHeartBeatScRsp

### ISSUE THREAD

**Issue by 7libra7** [IceDynamix/reliquary-archiver#78]
![Screenshot_2024-12-05-11-49-46-273_com termux](https://github.com/user-attachments/assets/e68a5c6f-f94a-46c0-914a-521a48a3692e)
problem building from source with --target release, missing module PlayerHeartBeatCsReq/PlayerHeartBeatScRsp

**Comment by IceDynamix** [comment]
fixed with https://github.com/IceDynamix/reliquary-archiver/commit/041932e181a6b3542f10323db9cc1611bb06b279 (https://github.com/IceDynamix/reliquary/pull/16)
